project: training-dgms
entity: platypus-dgm
sweep_name: grayscale_ve_sde_diffusions
count: 10000
delete_checkpoints: False


base_config:
  data:
    make_valid_loader: true
    train_batch_size: 128
    valid_batch_size: 128
    test_batch_size: 128
    additional_dataset_args:
      resize_image: [32, 32]
    


  trainer:
    trainer_cls: model_zoo.trainers.single_trainer.SingleTrainer
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 0.00005
    writer:
      tag_group: diffusion
      type: wandb
      entity: platypus-dgm
      project: training-dgms
      
    evaluator:
      valid_metrics: [loss]
      test_metrics: [loss]

    sample_freq: 1 # logs the samples after every two epochs
    max_epochs: 50
    early_stopping_metric: loss
    max_bad_valid_epochs: 50
    max_grad_norm: 1.0
    only_test: False
    progress_bar: True
      

  # Settings from the new configurations
  model:
    is_gae: false
    class_path: model_zoo.density_estimator.diffusions.VESDE_Diffusion
    init_args:
      # Data transform args (they are here because they might influence log_prob)
      flatten: False
      data_shape: [1, 32, 32]
      denoising_sigma: null
      dequantize: True
      scale_data: False
      scale_data_to_n1_1: True
      whitening_transform: False
      logit_transform: False
      clamp_samples: False

      score_network: model_zoo.networks.neural_networks.UNet
      score_network_kwargs:
        image_channels: 1 
        n_channels: 64
        ch_mults: [1, 2, 4, 4]
        is_attn: [False, False, True, True]
        n_blocks: 2

      T: 1.0
      beta_min: 0.1
      beta_max: 20.

      T: 1.0
      beta_min: 0.1
      beta_max: 20.
    

sweep_configuration:
  data:
    dataset:
      sweep_identifier: B_dataset
      sweep: True
      values: ['fashion-mnist', 'omniglot', 'mnist', 'emnist']