# This sweep contains the training configuration of all the RGB flow models 
# trained on a colorful image of size [3 x 32 x 32]
# This contains the Glow models and the Neural Spline Flows

project: training-dgms
entity: platypus-dgm
count: 10000

# Change the name of the run to an apprpriate one according to the configuration
# See the code for this for more information
run_name_changer:
  expression: |
    from meta_configurations import change_name 

  function_of_interest: change_name