# This sweep contains the training configuration of all the RGB flow models 
# trained on a colorful image of size [3 x 32 x 32]
# This contains the Glow models and the Neural Spline Flows

project: training-dgms
entity: platypus-dgm
count: 10000

