# This sweep compares the likelihood values of in and out of distribution
# for all the dataset pairs, containing the DGM generated ones
project: HP-tuning
entity: platypus-dgm
count: 10000
method: grid

# Change the name of the run to [in_distribution_dataset]_vs_[out_of_distribution_dataset]_[run_name]
# using the dysweep name changer for better readability
run_name_changer:
  expression: |
    from meta_configurations import *
  function_of_interest: hp_tuning_run_name_changer
