# This sweep compares different fast flow LID estimators for Gaussian projection examples
# These examples include projected samples from a Gaussian or a uniform distribution
project: intrinsic-dimensions
sweep_name: gaussian_projected_examples_fast_lid
entity: platypus-dgm
count: 10000
method: grid

# Change the name of the run to [in_distribution_dataset]_vs_[out_of_distribution_dataset]_[run_name]
# using the dysweep name changer for better readability
run_name_changer:
  expression: |
    from meta_configurations import *
  function_of_interest: intrinsic_dimension_run_name_changer
