data:
  dataset: fashion-mnist
  make_valid_loader: true
  train_batch_size: 1024
  valid_batch_size: 1024
  test_batch_size: 1024
  embedding_network: nvidia_efficientnet_b0

trainer:
  trainer_cls: model_zoo.trainers.single_trainer.SingleTrainer
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.001
  writer:
    logdir: runs
    make_subdir: True
    tag_group: flow
    type: wandb
    entity: dgm-l6
    project: training-dgms
    
  evaluator:
    valid_metrics: [loss]
    test_metrics: [loss]

  max_epochs: 120
  early_stopping_metric: loss
  max_bad_valid_epochs: 5
  max_grad_norm: 1.0
  only_test: False
  progress_bar: True
    

# Settings from the new configurations
model:
  is_gae: false
  class_path: model_zoo.density_estimator.flow.NormalizingFlow
  init_args:
    # Data transform args (they are here because they might influence log_prob)
    flatten: False
    data_shape: [1000]

    denoising_sigma: null
    dequantize: False
    scale_data: False
    whitening_transform: False
    logit_transform: False
    clamp_samples: False

    # Base distribution arguments (in this work the base is always Gaussian)
    base_distribution:
      class_path: nflows.distributions.StandardNormal
      init_args:
        shape: [1000]
    

    transform:
    - repeat_n: 3
      content:
        - class_path: nflows.transforms.normalization.ActNorm
          init_args:
            features: 1000
        - class_path: model_zoo.density_estimator.flow.ConfigurableCouplingTransform
          init_args: 
            coupling_transform_cls: nflows.transforms.PiecewiseRationalQuadraticCouplingTransform
            net:
              class_path: nflows.nn.nets.resnet.ResidualNet
              init_args:
                hidden_features: 512
                num_blocks: 3
            mask:
              dim: 1000
              flip: True
            tails: linear
            num_bins: 2
            tail_bound: 1.0
        
        - class_path: nflows.transforms.normalization.ActNorm
          init_args:
            features: 1000
        - class_path: model_zoo.density_estimator.flow.ConfigurableCouplingTransform
          init_args: 
            coupling_transform_cls: nflows.transforms.PiecewiseRationalQuadraticCouplingTransform
            net:
              class_path: nflows.nn.nets.resnet.ResidualNet
              init_args:
                hidden_features: 512
                num_blocks: 3
            mask:
              dim: 1000
              flip: False
            tails: linear
            num_bins: 2
            tail_bound: 1.0

    